### ISSUE TITLE
[Questions] I would like to know what you think about this.

### ISSUE THREAD

**Issue by naoto0826g** [YTLitePlus/YTLitePlus#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

![IMG_2622](https://github.com/user-attachments/assets/583df287-f06d-491b-afca-fbd32a53386d)

**Comment by mmupmip** [comment]
Oof, that doesn't look good

**Comment by trytolive** [comment]
after all the end user is the one who suffers. still have to thank all the developers, they are awesome until creative rights are respected!

**Comment by Yunogamer** [comment]
what the fuck is this stuck up guy's problem..? sigh.. he better add the stuff that ytlite plus has that ytlite doesnt then.

**Comment by mustafacakirogludev** [comment]
> what the fuck is this stuck up guy's problem..? sigh.. he better add the stuff that ytlite plus has that youtube plus doesnt then.

Comments like these make me agree with the OG developer. Do you realize if he stops working on his tweak this one will be unusable too? Also almost all necessary stuff are already there in his tweak, you can inject the rest easily on your own. He is doing his own thing, why are you acting like he owes you anything? He is not responsible of maintaining forks of his tweak.

**Comment by mmupmip** [comment]
> > what the fuck is this stuck up guy's problem..? sigh.. he better add the stuff that ytlite plus has that youtube plus doesnt then.
> 
> 
> 
> Comments like these make me agree with the OG developer. Do you realize if he stops working on his tweak this one will be unusable too? Also almost all necessary stuff are already there in his tweak, you can inject the rest easily on your own. He is doing his own thing, why are you acting like he owes you anything? He is not responsible of maintaining forks of his tweak.

+1 on that. He also literally stated the reason why right there. He's doing a service to the community, and has all the rights to change his project how he sees fit.

**Comment by Yunogamer** [comment]
> > what the fuck is this stuck up guy's problem..? sigh.. he better add the stuff that ytlite plus has that youtube plus doesnt then.
> 
> Comments like these make me agree with the OG developer. Do you realize if he stops working on his tweak this one will be unusable too? Also almost all necessary stuff are already there in his tweak(YTUHD, YouPiP, Youtube Dislikes, Sponsorblock etc.), you can inject the rest easily on your own. He is doing his own thing, why are you acting like he owes you anything? He is not responsible of maintaining forks of his tweak.
> 
> He is the reason we have YTLite and YTLite Plus and you are acting like just because he added a banner warning the users all he did 'till now is worthless. [YTLitePlus devs should've listened to his warning](https://github.com/YTLitePlus/YTLitePlus/issues/395#issuecomment-2324648842) and leave his banner alone. Go blame them if you are angry. It was obvious this will happen, [even I commented about it before](https://github.com/YTLitePlus/YTLitePlus/issues/395#issuecomment-2327047768). Honestly if I worked hard on something and other developers forked it and injected some stuff and got more stars, downloads etc. I'd be pissed, he is handling it better than I would.

the guy has all the precious donate links and credit etc posted everywhere, not like anything of his is "stolen", yet still not enough, so i got an idea! "make the users suffer cause i can"

**Comment by mustafacakirogludev** [comment]
> > > what the fuck is this stuck up guy's problem..? sigh.. he better add the stuff that ytlite plus has that youtube plus doesnt then.
> > 
> > 
> > Comments like these make me agree with the OG developer. Do you realize if he stops working on his tweak this one will be unusable too? Also almost all necessary stuff are already there in his tweak(YTUHD, YouPiP, Youtube Dislikes, Sponsorblock etc.), you can inject the rest easily on your own. He is doing his own thing, why are you acting like he owes you anything? He is not responsible of maintaining forks of his tweak.
> > He is the reason we have YTLite and YTLite Plus and you are acting like just because he added a banner warning the users all he did 'till now is worthless. [YTLitePlus devs should've listened to his warning](https://github.com/YTLitePlus/YTLitePlus/issues/395#issuecomment-2324648842) and leave his banner alone. Go blame them if you are angry. It was obvious this will happen, [even I commented about it before](https://github.com/YTLitePlus/YTLitePlus/issues/395#issuecomment-2327047768). Honestly if I worked hard on something and other developers forked it and injected some stuff and got more stars, downloads etc. I'd be pissed, he is handling it better than I would.
> 
> the guy has all the precious donate links and credit etc posted everywhere, not like anything of his is "stolen", yet still not enough, so i got an idea! "make the users suffer cause i can"

You talk like he is forcing you to use his tweak or forcing you to donate. You don't like how he is "making you suffer"? Flash news, you can stop using the tweak and use uyou or something 🤷 All I am saying is he is doing a lot, we can tolerate one pop-up he added. I like using his tweak, that's why I am saying all these, you do you dude.

**Comment by Balackburn** [comment]
The issue with **@dayanch96** and me has always been a lack of communication. He never told me he was frustrated by this project. On several occasions, he threw disguised digs at *YTLitePlus* or mocked the fact that I wasn't as good a developer as he was, indicating animosity even before "we" modified his tweak. I contacted him after he closed the source code of his tweak, as he posted an angry, enigmatic comment about people stealing his work. He didn't even reply to my message, which seemed like contempt, as I had written a long comment and asked him if there was anything he disliked about *YTLitePlus* and how we could make things better. I had to contact him on Reddit to get a response, and he told me that the spikes weren't related to *YTLitePlus* and that he didn't have a problem with us, but now with this, I'm not sure it wasn't related.

He never directly contacted me to complain or ask for anything (except in the recent incompatible popup warning issue thread, and I didn't even see his comment at first).

I started this project alone as I was using *CercubePlusExtra*, and it wasn't maintained. When I saw that **@dayanch96** released a new tweak, I asked if I could use it and forked *CercubePlusExtra* and edited it to include *YTLite* instead of *Cercube*, mainly for my own use. I promoted the app on Reddit, created a website, and an Altstore source for easy sideloading, and **@dayanch96** didn't seem to have a problem with that at all. I think this helped *YTLite* gain popularity over other tweaks more than anything else could have done.

After that, **@arichorn** helped me on the project; I was happy to have someone with more knowledge than me working on this. This project was mainly mine, but as I am not really a developer, I was happy to have other people working on it. That's why I also added **@bhackel** as a collaborator, who took completely autonomous decisions that didn't necessarily fit my vision for the app (like adding a toggle to hide the HUD from *YTLite*, or adding a *YTLitePlus* button to play videos from files). But he helped a lot in keeping this project alive, and I thank him for the work he did. There wasn't much directive or communication between us; mistakes were made for sure, but we never wanted to disrespect **@dayanch96**.  He is acting as if there is no reason for this project, when in fact there is. Maybe we did better presentation/marketing than him and that's why it got more popular, we didn't steal his users and even made the user base bigger.

At first *YTLite* (like the name suggests) was a lite but complete YouTube tweak, but there were a lot of things missing. It made absolute sense at the time to have *YTLitePlus* with more features and tweaks injected in it, but over time, the tweak evolved into something more complete. He even added a download feature (even though he stated that he would never add it) and renamed it from *YTLite* to *YTPlus*, which made *YTLitePlus* less relevant and confusing over time.

### Future Plans

For the future of this project, I plan to rename it to **YTPlusPlus** to make more sense and to delete the *YTLitePlus* tweak completely from the app for now. First, to avoid showing the incompatible popup warning, and second, this should satisfy **@dayanch96** with bug report

I plan to keep this alive, first because I use it myself, and I know a lot of users want this to continue.

After that, I think this tweak should be rewritten from scratch to avoid bug reports being sent to **@dayanch96**.
**@arichornloverALT**, would you be willing to rethink the tweak from scratch to not have a "badly written tweak" and include only extra features that make sense?


### Respect for @dayanch96

Please respect **@dayanch96**. The insults directed at him are absolutely intolerable. There is no *YTLitePlus* without **@dayanch96**. He has done an extraordinary job for free and is a very talented developer. 

If you like *YTPlus*, please consider supporting him through donation:  
- [Buy me a coffee](https://buymeacoffee.com/dayanch96)  
- [Patreon](https://www.patreon.com/dayanch96)

**Comment by bhackel** [comment]
Hey, I’m sorry I made some emotion-triggered decisions recently. I’m going to take some time off to cool my mental, and then if I feel like I should come back, without escalating tensions again, then I might. Thanks

**Comment by Balackburn** [comment]
> Hey, I’m sorry I made some emotion-triggered decisions recently. I’m going to take some time off to cool my mental, and then if I feel like I should come back, without escalating tensions again, then I might. Thanks

Don't think too much about it, it shouldn't have any impact on you personally.

**Comment by dayanch96** [comment]
@Balackburn which messenger you're using? Dm me when you have free time: Telegram: dvntm, Discord: dayanch96

**Comment by JudeTheTechSavvyDude** [comment]
When is the next Release of YTLitePlus with the fix for the bypass screen is coming out?

**Comment by FrankTheTank908** [comment]
Also getting the incompatible tweaks screen every launch. Hope it will be fixed soon

**Comment by Prakyy** [comment]
The dev should make it appear on the first launch after installing/updating the app, making it pop up every time the app launches is not necessary I think?

**Comment by Balackburn** [comment]
> > The dev should make it appear on the first launch after installing/updating the app, making it pop up every time the app launches is not necessary I think?
> 
> 
> 
> That wouldn’t be a smart idea.
> 
> I think what the pop-up needs in **YouTube Plus** is a new button next to “I Accept All Risks” saying “Remind me in 7 days”
> 
> adding a reminder to the pop-up would be a better way then it appearing everytime the app is launched, the pop-up would likely be hidden until the 7 days are over and it’ll reappear.
> 
> 
> 
> If the **YouTube Plus** developer sees this, then this idea might not be smart, and I have the code to add reminders but I won’t because I want don’t want to disrespect the dev like I said in https://github.com/YTLitePlus/YTLitePlus/commit/5eb16b09b23503dddcbb5e5da0a18b394e6b48dd

@dayanch96

**Comment by Prakyy** [comment]
> > The dev should make it appear on the first launch after installing/updating the app, making it pop up every time the app launches is not necessary I think?
> 
> I think what the pop-up needs in **YouTube Plus** is a new button next to “I Accept All Risks” saying “Remind me in 7 days”. Adding a reminder to the pop-up would be a better approach than having it appear every time the app is launched. The pop-up would be hidden until the 7 days are over, at which point it would reappear, but then you can just repeat the process by hitting the “Remind me in 7 days” button. This is essentially how it would work.
> 
> I do have the code to add reminders, but I won’t implement it because I don’t want to disrespect the developer, as I mentioned in this commit. [5eb16b0](https://github.com/YTLitePlus/YTLitePlus/commit/5eb16b09b23503dddcbb5e5da0a18b394e6b48dd)
> 
> But overall this idea for the pop-up I had in mind may not be good because I don’t know your opinion about this but hoping it’s useful.

Is it possible that you link the patch to remove the banner so I can merge in my own fork??

People building the ipa themselves would have more sense not to complain. I really like ytliteplus but the banner, more or less everytime, I open the app is getting very dizzying.

**Comment by dayanch96** [comment]
it will be less annoying on 5.1
