### ISSUE TITLE
[Bug] Unable to save videos offline using YouTube's built-in download feature

### ISSUE THREAD

**Issue by Prakyy** [YTLitePlus/YTLitePlus#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 13 Pro

### Sideload method

Esign

### Tweak version

YTLitePlus - v19.34.2-5.0.2

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Trying to download any YouTube video just gets stuck at the 'waiting to download...' stage. It downloads maybe 50% then proceeds to sit at waiting. I cannot pause and resume it, only cancel or delete the download options are available.
  
![photo_2024-09-13_20-48-44](https://github.com/user-attachments/assets/0bc00d9f-d2fe-4330-8e9f-d72fb41c1a76)

### Steps to reproduce the issue

1. Disable download manager from YouTube plus settings
2. Open any video
3. Click download and go to downloads tab
4. Find the video to not be downloading but 'waiting to download...'

### Additional context

1. Video downloading works normally with the stock YouTube client.
2. It has never worked for me on any ytliteplus versions, not just this one.

**Comment by AlteredCabr0n** [comment]
Have you kept the same preferences each time you upgraded or did you do a clean install each time?

There may be a conflicting YTABConfig flag in the A/B settings so I'd recommend going there and searching "download" to see if anything looks off.

**Comment by Prakyy** [comment]
I've tried not changing any setting except disabling download manager as well. There are a lot of A/B flags in settings and they seem to be fine. Are you able to download videos properly?

**Comment by AlteredCabr0n** [comment]
> Are you able to download videos properly?

I am. But using a much older device so 🤷🏾‍♂️

**Comment by asportnoy** [comment]
Might be worth noting that I also experienced this same issue with various other YouTube tweaks over the past 2 years or so, including uYouPlus and uYouEnhanced. I know those apps have a lot of tweaks in common with YTLitePlus, so it's possible one of those are the issue?

**Comment by Prakyy** [comment]
I don't think it's the tweaks. I installed the vanilla YouTube IPA using an enterprise cert, and it still doesn't download videos.

**Comment by Balackburn** [comment]
> I don't think it's the tweaks. I installed the vanilla YouTube IPA using an enterprise cert, and it still doesn't download videos.

I can't test this myself as I don't have premium, probably linked to entreprise certificate, can you try with Sideloadly with your Apple ID, thank you

**Comment by Prakyy** [comment]
> > I don't think it's the tweaks. I installed the vanilla YouTube IPA using an enterprise cert, and it still doesn't download videos.
> 
> I can't test this myself as I don't have premium, probably linked to entreprise certificate, can you try with Sideloadly with your Apple ID, thank you

Yeap, just installed youtube with sideloadly and the downloads seem to work. Now... what issue would the enterprise cert be causing. Shouldn't it have more entitlements?

Oh, and I noticed downloaded videos are in avc1 even if streaming videos uses vp9. Compared to YouTube downloaded from app store which has vp9 for both streaming and downloaded videos.

**Comment by vikasbhatia** [comment]
Hey, I had this exact same issue which I solved so I thought I’d add to the conversation here!

I use a KravaSign cert with Feather, so I asked their Discord support. They pointed me to a guide which I’m attaching as a screenshot of their guide but here’s the overview of what I did:

* Opened my .mobileprovision file in ESign, and looked for the “App ID”. This was in the format `<random characters>.com.xx.xx`
* Copied the `com.xx.xx` part.
* Installed a new copy of YouTube, changing the bundle ID from the default `com.google.ios.youtube` to what I copied from the App ID.

The downloads immediately started working.

Maybe it’s worth a shot for you as well!

Be aware that there are some caveats to doing this:

* If I need to update my app, I need to use the same bundle ID every time. I use Feather to sign and install apps and that allows you to set up presets for bundle ID replacements, so I just did that. Now every time I try to install a YouTube IPA, it’ll look for the default bundle ID and replace it so I don’t need to copy paste over it.
* For obvious reasons I cannot reuse this bundle ID in case another app shows similar behaviour - but I don’t have anything else that needs it so I’m good.
* Notifications apparently won’t work but I didn’t care about this either as I had YT notifications off anyway.

PS. also, I cannot for the life of me find my source for this (I will edit it in if I do - it was a comment on reddit or telegram) but I read that downloads worked without a problem on uYou 3.0.2 or a lower version, and these issues started in the newer versions due to the way Apple changed something about sideloading. 

You could give a lower YTLite/uYou/whatever version a try and with a little trial and error, see if that works without my workaround above.

I hope this helps you and anyone googling the same issue like I was!

![KravaSign Tutorial](https://github.com/user-attachments/assets/37b288e5-53dc-4ec1-90c5-bc6fc909bbb2)

**Comment by Prakyy** [comment]
@vikasbhatia hahaha that worked. I've migrated from android where sideloading used to be so easy, so I had to wrap my head around certs, entitlements and the like on iOS, and it's pretty annoying.

I got the AppID from eSign for my cert (using a revoked enterprise cert) and everything works now. It was working with free developer account signed YouTube too, but now I don't have to resign every 7 days. 

Main issues with the enterprise cert were:
- If you play a media, tapping the title on the lock screen media controls should take you to the app - they didn't for me
- An app asking to import some file from the internal storage couldn't - tapping on the file did nothing

Since these issues were across any app I sideloaded, I concluded it was an entitlements issue and I should buy a cert from a distributor like KravaSign, but now you're mentioning that you had issues with these paid certs as well, so now I'm back to square one.

Anyway, using the AppID as the bundleID of YouTube did the trick, now I am able to download videos and the media controls on the lockscreen do open the YouTube app - though there was an issue with the free dev acc signed version where the downloaded video would expire after a day with the error 'premium device limit exceeded', which may or may not be an accurate error, but I will be looking out for that with this method.

Thanks for the amazing write-up, I can finally use YouTube normally.

**Comment by vikasbhatia** [comment]
I’m so happy that worked for you! You’re very welcome.

I specifically wanted to comment even though this issue was closed because you’re the only search result I initially found that described my exact issue, and I completely empathised haha. I guess not a lot of people use YouTube’s built-in downloader? Though the quality is capped at 360p, I find it far more convenient to access downloads within the app instead of bouncing between others. Most of them are just podcasts that I listen to with screen off but occasionally want to see the video too.

Anyway, I can’t tell you the number of times this has happened to me:

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

So saving someone else that pain is a win. Have a great week.
